#! /usr/bin/env bash
# first start by detecting the distribution name and version number
# then use the result of that to determine which package manager to use

# **********************************
# THIS IS NOT READY AND NEEDS WORK
# **********************************

# "OS_TYPE" & VERSION variable comes from here:
source ./DetectOS.sh

USER_EMAIL="bretlinne@gmail.com"
USER_NAME="Bret Linne"
PLATFORM="unknown"
unamestr=`uname`


echo "OS Type: ${OS_TYPE}"
echo "Version: ${VERSION}"
function GitSetup(){
	printf "${LT_GREEN} Detected OS is: ${LT_BLUE}${OS_TYPE}${NC}\n"
	mkdir ~/Git
	case ${OS_TYPE} in
	"CentOS Linux")
		sudo yum install git
		;;
	"Ubuntu")
		sudo apt update
		sudo apt install git
		;;
	esac
	git --version
	git config --global user.email "${USER_EMAIL}"
	git config --global user.name "${USER_NAME}"
	git config --global push.default matching
}
