#! /usr/bin/env bash
# first start by detecting the distribution name and version number
# then use the result of that to determine which package manager to use

# **********************************
# THIS IS NOT READY AND NEEDS WORK
# **********************************

if [ -f /etc/os-release ]; then
    # freedesktop.org & systemd
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
elif type lsb_release >/dev/null 2>$1; then
    # linuxbase.org
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)    
USER_EMAIL="bretlinne@gmail.com"
USER_NAME="Bret Linne"
OS_TYPE=""
PLATFORM="unknown"
unamestr=`uname`

IF [[ "$unamestr" == "Linux" ]]; THEN
  PLATFORM='linux'
ELIF [[ "$unamestr" == "CentOS" ]]; THEN
  PLATFORM='

FI
function {
  mkdir ~/Git
  sudo yum install git
  git config --global user.email "${USER_EMAIL}"
  git config --global user.name "${USER_NAME}"
  git config --global push.default matching

}
